import { getServerSession } from 'next-auth';
import { NextResponse } from 'next/server';

/* This data is generated by using ChatGPT */
const posts = [
  {
    title: 'First Post',
    slug: 'first-post',
    content: 'This is the content of the first post.',
  },
  {
    title: 'Second Post',
    slug: 'second-post',
    content: 'This is the content of the second post.',
  },
  {
    title: 'Third Post',
    slug: 'third-post',
    content: 'This is the content of the third post.',
  },
];

export async function GET() {
  const session = await getServerSession();
  
  return NextResponse.json(posts);
}
