import { NavMenu } from '@/components/NavMenu';
import './globals.css';
import { Inter } from 'next/font/google';
import AuthProvider from '@/context/AuthProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className="flex flex-col gap-3 p-6 ">
            <NavMenu />
            {children}
          </div>
        </body>
      </html>
    </AuthProvider>
  );
}
